yatube/about/urls.py
from django.urls import path
from about import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

# Это колдограмма, чтобы в режиме отладки работали картинки
# Обычно раздачей картинок занимается сервер
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
        help_text='Введите заголовок группы'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Введите описание группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Группа',
        help_text='Введите название группы, к которой будет относиться пост'
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу, к которой будет относиться пост'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Загрузите заглавную картинку поста',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст коммента',
        help_text='Введите текст коммента'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Коммент',
        help_text='Выберите пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коммента',
        help_text='Выберите автора'
    )

    class Meta:
        verbose_name = 'Коммент'
        verbose_name_plural = 'Комменты'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Выберите пользователя'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Выберите автора'
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_follow'
            ),
        )
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return (f'Подписчик {self.user.username},'
                f'автор {self.author.username}')

yatube/posts/forms.py
from django import forms
from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from posts.models import Post, Group, User, Follow
from posts.forms import PostForm, CommentForm
from yatube.settings import POSTS_IN_PAGE, CACHE_TIME


@cache_page(CACHE_TIME)
def index(request):
    post_list = Post.objects.all().select_related('group','author')
    paginator = Paginator(post_list, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    paginator = Paginator(post_list, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
        'title': f'Записи сообщества {slug}'
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').all()
    paginator = Paginator(post_list, POSTS_IN_PAGE)
    page_namber = request.GET.get('page')
    page_obj = paginator.get_page(page_namber)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'title': f'Профайл пользователя {username}',
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related('author','group'), pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'title': f'Пост {post}'
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(request.POST, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {
        'form': form,
        'title': 'Новый пост',
        'groups': groups
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
        'title': 'Измененение поста',
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user).select_related('author','group')
    paginator = Paginator(posts, POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(
        user=request.user,
        author=author
    )
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
 {{ title }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {{ title }}             
        </div>
        <div class="card-body">        
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}            
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                {{ form.text.label }}                  
                <span class="required text-danger" >*</span>                  
              </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text" autofocus> {{ form.instance.text }}
                </textarea>                
              <small id="id_text-help" class="form-text text-muted">
                {{ form.text.help_text }}
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                {{ form.group.label }}                
              </label>
              <select name="group" class="form-control" id="group.id">
                {% for group in form.group %}
                  {{ group }}
                {% endfor %}
              </select>
              <small id="id_group-help" class="form-text text-muted">
                {{ form.group.help_text }} 
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image">
                Картинка                      
              {% if is_edit %}
                на данный момент: 
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                <input type="checkbox" name="image-clear" id="image-clear_id">
                <label for="image-clear_id">Очистить</label><br>
                </p>
              </label>
                Изменить:
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
              {% else %}
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
              </label>
              {% endif %}                      
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<div class="container py-5">
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>    
    <article>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    </article>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>  
{% include 'posts/includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<div class="container py-5">
  <h1> {{ group.title }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>    
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
</div>
{% include 'posts/includes/paginator.html' %}   
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<div class="container py-5">
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>    
    <article>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    </article>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>  
{% include 'posts/includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
      {% if post.group %} 
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ post.author }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ post.author.posts.count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.author.username == user.username %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        редактировать запись
      </a>
    {% endif %}  
  </article>
</div>

{% include 'posts/includes/comments.html' %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <h1>Все посты пользователя {{ author.username }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% if request.user != author %}
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
      </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
  {% endif %}
  {% for post in page_obj %}           
    <article>
      <ul>
        <li>
          Автор: {{ author }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}  
        </li>
      </ul>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text }} </p>
      </article>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
    {% if post.group %}        
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}        
    <hr>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
</div>
{% include 'posts/includes/paginator.html' %}   
{% endblock %} 